---
abstract: 'enable your scripts to autoinstall their dependencies'
author:
  - 'Alex Kapranoff <kappa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::ThinPacker
name: App-ThinPacker
no_index:
  directory:
    - inc
    - t
requires:
  PPI: 0
  Pod::Find: 0
  Pod::Usage: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
